JBMapp/Controllers/ProductCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Data;
using Core.Data.Models;
using System.IO;
using System.Data.OleDb;
using System.Data;
using JBMapp.ADUC;

namespace JBMapp.Controllers
{
    public class ProductCodeController : Controller
    {
        // GET: ProductCode
        public ActionResult Index()
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            IEnumerable<ProductCode> pc = ProductCodeDataAccess.GetProductCodes();
            return View(pc);
        }

        [HttpGet]
        public ActionResult EditProductCode(string pId)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            ProductCode Pc = ProductCodeDataAccess.GetProductCode(pId);

            ViewBag.ScriptTemplate = new SelectList(ScriptDataAccess.GetScripts(), "ScriptTemplate", "ScriptName", Pc.ScriptTemplate);
            return View(Pc);
        }

        [HttpPost]
        public ActionResult EditProductCode(ProductCode pc)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            string logI = HttpContext.User.Identity.Name;
            ProductCodeDataAccess.UpdateProductCode(pc, logI);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UploadProducts()
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);
            //IEnumerable<ProductCode> pcs = null;
            return View();
        }

        [HttpPost]
        public ActionResult UploadProducts(HttpPostedFileBase file, List<ProductCode> model, string Submit)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            string logI = HttpContext.User.Identity.Name;
            List<ProductCode> pcs = new List<ProductCode>();
            List<ProductCode> RetPcs = new List<ProductCode>();
            string err;

            if (Submit == "Upload")
            {
                try
                {
                    pcs = LoadProductCodes(file, out err);

                    if (err == null)
                    {
                        foreach (ProductCode pc in pcs)
                        {
                            bool exist = ProductCodeDataAccess.CheckIfExist(pc.PCode);
                            if (exist == false)
                            {
                                RetPcs.Add(pc);
                            }
                        }

                        //future function
                        //foreach (ProductCode pc in pcs)
                        //{
                        //    bool forUpdating = ProductCodeDataAccess.CheckIfForUpdating(pc);
                        //    if (forUpdating == true)
                        //    {
                        //        RetPcs.Add(pc);
                        //    }
                        //}
                    }
                    else
                    {
                        ViewData["Error"] = err;
                        return View();
                    }
                }
                catch (Exception ex)
                {
                    ViewData["Error"] = ex.Message;
                    return View();
                }
                if (RetPcs.Count() <= 0)
                {
                    ViewData["Error"] = "No New ProductCode Found!";
                }
                ViewBag.ScriptTemplate = new SelectList(ScriptDataAccess.GetScripts(), "ScriptTemplate", "ScriptName");
                return View(RetPcs);
            }
            else
            {
                if (model != null)
                {
                    foreach (ProductCode pc in model)
                    {
                        try
                        {
                            ProductCodeDataAccess.InsertProduct(pc, logI.Split('\\').LastOrDefault());
                        }
                        catch (Exception ex)
                        {
                            ViewData["Error"] = ex.Message;
                            ViewBag.ScriptTemplate = new SelectList(ScriptDataAccess.GetScripts(), "ScriptTemplate", "ScriptName");
                            return View(model);
                        }
                    }
                }
                ViewData["Success"] = "Product Code Successfully uploaded!";
                return RedirectToAction("Index");
            }
        }

        public List<ProductCode> LoadProductCodes(HttpPostedFileBase file, out string errMsg)
        {
            List<ProductCode> mas = new List<ProductCode>();
            if (Request.Files.Count > 0)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/MediaFiles/"), fName);
                    file.SaveAs(path);
                    string conStr;

                    string ext = Path.GetExtension(path);
                    if (ext.ToLower().Trim() == ".xls")
                    {
                        conStr = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + path + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                        errMsg = null;
                        return LoadExcel(path, conStr);

                    }
                    else if (ext.ToLower().Trim() == ".xlsx")
                    {
                        conStr = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                        errMsg = null;
                        return LoadExcel(path, conStr);
                    }
                    else
                    {
                        errMsg = "Invalid File!";
                        return null;
                    }

                }
            }

            errMsg = null;
            return mas.ToList();
        }

        public static List<ProductCode> LoadExcel(string strFilePath, string conStr)
        {
            OleDbConnection oledbConn = new OleDbConnection(conStr);
            DataTable dt = new DataTable();
            List<ProductCode> pcs = new List<ProductCode>();

            try
            {
                if (oledbConn.State == ConnectionState.Closed)
                { oledbConn.Open(); }

                using (OleDbCommand cmd = new OleDbCommand("SELECT * FROM [Sheet1$] WHERE [Product Code] IS NOT NULL", oledbConn))
                {
                    OleDbDataAdapter oleda = new OleDbDataAdapter();
                    oleda.SelectCommand = cmd;
                    DataSet ds = new DataSet();
                    oleda.Fill(ds);
                    dt = ds.Tables[0];

                    foreach (DataRow dr in dt.Rows)
                    {
                        ProductCode pc = new ProductCode();
                        pc.Brand = dr["Brand"].ToString();
                        pc.PCode = dr["Product Code"].ToString();
                        pc.MediaCompany = dr["Media Company"].ToString();
                        pc.Script = dr["Script"].ToString();
                        pc.Offer = dr["Offer"].ToString();
                        pcs.Add(pc);
                    }
                }
            }
            catch 
            {
                oledbConn.Close();
            }
            finally
            {
                oledbConn.Close();
            }
            return pcs;
        }
    }
}

JBMapp/Views/ProductCode/EditProductCode.cshtml
@using Core.Data.Models;

@model ProductCode
@{
    ViewBag.Title = "EditProductCode";
}

<h3>EditProductCode</h3>



<div class="container">
    <div class="well">
        @using (Html.BeginForm("EditProductCode", "ProductCode",FormMethod.Post))
        {
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="Brand">Brand</label>
                        @Html.TextBoxFor(m => m.Brand, new { @class = "form-control", @id = "Brand" })
                    </div>

                    <div class="form-group">
                        <label for="PCode">Product Code</label>
                        @Html.TextBoxFor(m => m.PCode, new { @class = "form-control", @id = "PCode" })
                    </div>

                    <div class="form-group">
                        <label for="Script">Script</label>
                        @Html.TextBoxFor(m => m.Script, new { @class = "form-control", @id = "Script" })
                    </div>

                    <div class="form-group">
                        <label for="Offer">Offer</label>
                        @Html.TextBoxFor(m => m.Offer, new { @class = "form-control", @id = "Offer" })
                    </div>

                    <div class="form-group">
                        <label for="BrandCode">Brand Code</label>
                        @Html.TextBoxFor(m => m.BrandCode, new { @class = "form-control", @id = "BrandCode" })
                    </div>

                    <div class="form-group">
                        <label for="MediaCompany">Media Company</label>
                        @Html.TextBoxFor(m => m.MediaCompany, new { @class = "form-control", @id = "MediaCompany" })
                    </div>

                    <div class="form-group">
                        <label for="ScriptTemplate">Script Template</label>
                        @*@Html.TextBoxFor(m => m.ScriptTemplate, new { @class = "form-control", @id = "ScriptTemplate"})*@
                        @Html.DropDownList("ScriptTemplate", null, new { @class = "form-control", @id = "ScriptTemplate" })

                    </div>
                    <div class="col-lg-6 text-right">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        }
    </div>

    @if (ViewData["Err"] != null)
    {
        <script type="text/javascript">
            alert('@ViewData["Err"].ToString()');
        </script>
    }
</div>

JBMapp/Views/ProductCode/Index.cshtml
@using Core.Data.Models;
@model IEnumerable<ProductCode>

@{
    ViewBag.Title = "Index";
}

<h3>Product Code Master</h3>

@Html.ActionLink("Upload List Of Products", "UploadProducts", "ProductCode")

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>Brand</th>
            <th>Product Code</th>
            <th>Script</th>
            <th>Offer</th>
            <th>Brand Code</th>
            <th>Media Company</th>
            <th>Script Template</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ProductCode item in Model)
        {
            <tr>
                <td>@item.Brand</td>
                <td>@Html.ActionLink(@item.PCode, "EditProductCode", "ProductCode", new { @pId = @item.PCode }, null) </td>
                <td>@item.PCode</td>
                <td>@item.Script</td>
                <td>@item.Offer</td>
                <td>@item.BrandCode</td>
                <td>@item.MediaCompany</td>
                <td>@item.ScriptTemplate</td>
            </tr>
        }
    </tbody>

</table>

JBMapp/Views/ProductCode/UploadProducts.cshtml
@using Core.Data.Models;
@model  IList<ProductCode>

@{
    ViewBag.Title = "Upload Product Code";
}


<h3>Upload Product Code</h3>
<br />

@using (Html.BeginForm("UploadProducts", "ProductCode", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmMain" }))
{
    <div class="container">
        <div class="row">
            <div class="col-lg-12 well">
                <div class="row">
                    <div class="col-lg-3">
                        <input type="file" name="file" class="form-control" />
                    </div>
                    <div class="col-lg-6">
                        <input class="btn btn-primary" type="submit" name="Submit" id="Submit" value="Upload" />
                    </div>

                </div>
            </div>
        </div>
    </div>
    if (Model != null)
    {
        int ctr = 0;
        <table class="table table-bordered table-condensed" id="ProductCodes">
            <thead>
                <tr>
                    <th>Brand</th>
                    <th>Product Code</th>
                    <th>MediaCompany</th>
                    <th>Script</th>
                    <th>Offer</th>
                    <th>Script</th>
                </tr>
            </thead>
            <tbody>

              
               @foreach (ProductCode pc in Model)
                {
                <tr>
                    <td>
                        @pc.Brand
                        @Html.HiddenFor(m => m[ctr].Brand)
                    </td>
                    <td>
                        @pc.PCode
                        @Html.HiddenFor(m => m[ctr].PCode)
                    </td>
                    <td>
                        @pc.MediaCompany
                        @Html.HiddenFor(m => m[ctr].MediaCompany)
                    </td>
                    <td>
                        @pc.Script
                        @Html.HiddenFor(m => m[ctr].Script)
                    </td>
                    <td>
                        @pc.Offer
                        @Html.HiddenFor(m => m[ctr].Offer)
                    </td>
                    <td>
                        @*@Html.DropDownList("ScriptTemplate",null, new { @class = "form-control", @id = "ScriptTemplate" })*@
                        <select name="[@ctr].ScriptTemplate" class="form-control" id="ScriptTemplate">
                            @foreach (SelectListItem ps in @ViewBag.ScriptTemplate)
                            {
                                <option value="@ps.Value">@ps.Text</option>
                            }
                            <option value="" selected>Please Select</option>
                        </select>
                    </td>
                </tr>
                ctr = ctr + 1;
                }


            </tbody>
        </table>

        <input type="submit" class="btn btn-primary" name="Submit" value="Process" />
    }
}

@{
    if (ViewData["Error"] != null)
    {
        <script>
            alert('@ViewData["Error"].ToString()');
        </script>
    }
    if (ViewData["Success"] != null)
    {
        <script>
            alert('@ViewData["Success"].ToString()');
        </script>
    }
}