JBMapp/Controllers/ScriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Data;
using Core.Data.Models;
using System.Data;
using JBMapp.ADUC;


namespace JBMapp.Controllers
{
    public class ScriptController : Controller
    {
        public ActionResult Index()
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            IEnumerable<PromoScript> scripts = ScriptDataAccess.GetScripts().ToList();
            return View(scripts);
        }

        [HttpGet]
        public ActionResult AddNewScript()
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            ViewBag.BrandCode = new SelectList(ScriptDataAccess.GetBrands(), "BrandCode", "BrandName","");
            return View();
        }

        [HttpPost]
        public ActionResult AddNewScript(PromoScript ps)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);
            try
            {
                string logI = HttpContext.User.Identity.Name;
                int ret = ScriptDataAccess.SaveNewScript(ps, logI.Split('\\').LastOrDefault());
                if (ret > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["Err"] = "Script Template Already Exist!";
                }
            }
            catch (Exception ex)
            {

                ViewData["Err"] = ex.Message;
            }
            return View(ps);
        }

        [HttpGet]
        public ActionResult EditScript(string tId)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);

            PromoScript ps = new PromoScript();
            DataRow dr = ScriptDataAccess.GetScript(tId);
            ps.ScriptTemplate = dr["ScriptCode"].ToString();
            ps.ScriptName = dr["ScriptName"].ToString();
            ps.BiScriptCode = dr["BIScriptCode"].ToString();
            ps.CoreOfferSalesTax = dr["CoreOfferSalesTax"].ToString();
            ps.CrossSalesTax = dr["CrossSaleTax"].ToString();
            ps.Description = dr["Description"].ToString();
            ps.BrandCode = dr["BrandCode"].ToString();
            ViewBag.OldScriptCode = dr["ScriptCode"].ToString();
            ViewBag.BrandCode = new SelectList(ScriptDataAccess.GetBrands(), "BrandCode", "BrandName", ps.BrandCode);
            return View(ps);
        }

        [HttpPost]
        public ActionResult EditScript(PromoScript ps, string OldScriptCode)
        {
            ActiveDirectoryWeb ad = new ActiveDirectoryWeb();
            string[] usr = ad.SearchActiveDirectory(HttpContext.User.Identity.Name).Split('|');
            ViewBag.IsAdmin = DataAccess.AdminAccess(usr[1]);
            string logI = HttpContext.User.Identity.Name;
            try
            {
                ScriptDataAccess.UpdateScript(ps, OldScriptCode, logI.Split('\\').LastOrDefault());
            }
            catch
            {
                ViewBag.OldScriptCode = OldScriptCode;
                return View(ps);
            }
            return RedirectToAction("Index");
        }
    }
}

JBMapp/Views/Script/AddNewScript.cshtml
@using Core.Data.Models;
@model PromoScript
@{
    ViewBag.Title = "AddNewScript";
}

<h2>Add New Script</h2>


<div class="container">
    <div class="well">
        @using (Html.BeginForm("AddNewScript", "Script"))
        {
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="Template">Template</label>
                        @Html.TextBoxFor(m => m.ScriptTemplate, new { @class = "form-control", @id = "Template" })
                    </div>

                    <div class="form-group">
                        <label for="ScriptName">Script Name</label>
                        @Html.TextBoxFor(m => m.ScriptName, new { @class = "form-control", @id = "ScriptName" })
                    </div>

                    <div class="form-group">
                        <label for="BiScriptCode">Bi Script Code</label>
                        @Html.TextBoxFor(m => m.BiScriptCode, new { @class = "form-control", @id = "BiScriptCode" })
                    </div>

                    <div class="form-group">
                        <label for="Description">Script Description</label>
                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @id = "Description" })
                    </div>

                    <div class="form-group">
                        <label for="CoreOfferSalesTax">Core Offer Sales Tax</label>
                        @Html.TextBoxFor(m => m.CoreOfferSalesTax, new { @class = "form-control", @id = "CoreOfferSalesTax" })
                    </div>

                    <div class="form-group">
                        <label for="CrossSalesTax">Cross Sales Tax</label>
                        @Html.TextBoxFor(m => m.CrossSalesTax, new { @class = "form-control", @id = "CrossSalesTax" })
                    </div>

                    <div class="form-group">
                        <label for="BrandCode">BrandCode</label>
                        @*@Html.TextBoxFor(m => m.BrandCode, new { @class = "form-control", @id = "BrandCode", @maxlength = "2" })*@
                     @Html.DropDownList("BrandCode", null, new { @class = "form-control" })
                 
                    </div>
                    <div class="col-lg-6 text-right">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        }
    </div>

    @if (ViewData["Err"] != null)
    {
        <script type="text/javascript">
            alert('@ViewData["Err"].ToString()');
        </script>
    }
</div>

JBMapp/Views/Script/EditScript.cshtml
@using Core.Data.Models;
@model PromoScript

@{
    ViewBag.Title = "EditScript";
}

<h2>EditScript</h2>

<div class="container">
    <div class="well">
        @using (Html.BeginForm("EditScript", "Script"))
        {
            @Html.Hidden("OldScriptCode", @Model.ScriptTemplate)

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="Template">Template</label>
                        @Html.TextBoxFor(m => m.ScriptTemplate, new { @class = "form-control", @id = "Template" })
                    </div>

                    <div class="form-group">
                        <label for="ScriptName">Script Name</label>
                        @Html.TextBoxFor(m => m.ScriptName, new { @class = "form-control", @id = "ScriptName" })
                    </div>

                    <div class="form-group">
                        <label for="BiScriptCode">Bi Script Code</label>
                        @Html.TextBoxFor(m => m.BiScriptCode, new { @class = "form-control", @id = "BiScriptCode" })
                    </div>

                    <div class="form-group">
                        <label for="Description">Script Description</label>
                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @id = "Description" })
                    </div>

                    <div class="form-group">
                        <label for="CoreOfferSalesTax">Core Offer Sales Tax</label>
                        @Html.TextBoxFor(m => m.CoreOfferSalesTax, new { @class = "form-control", @id = "CoreOfferSalesTax" })
                    </div>

                    <div class="form-group">
                        <label for="CrossSalesTax">Cross Sales Tax</label>
                        @Html.TextBoxFor(m => m.CrossSalesTax, new { @class = "form-control", @id = "CrossSalesTax" })
                    </div>

                    <div class="form-group">
                        <label for="BrandCode">BrandCode</label>
                        @*@Html.TextBoxFor(m => m.BrandCode, new { @class = "form-control", @id = "BrandCode", @maxlength = "2" })*@
                        @Html.DropDownList("BrandCode", null, new { @class = "form-control" })

                    </div>

                    <div class="col-lg-6 text-right">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        }
    </div>

    @if (ViewData["Err"] != null)
    {
        <script type="text/javascript">
            alert('@ViewData["Err"].ToString()');
        </script>
    }
</div>

JBMapp/Views/Script/Index.cshtml
@using Core.Data.Models;

@model IEnumerable<PromoScript>



<h2>Script</h2>
@Html.ActionLink("Add New Script", "AddNewScript", "Script")
<table class="table table-bordered table-condensed" id="Script">
    <thead>
        <tr>
            <th>Template</th>
            <th>Script Name</th>
            <th>Bi ScriptCode</th>
            <th>Script Description</th>
            <th>Core Offer Sales Tax</th>
            <th>Cross Sales Tax</th>
         
        </tr>
    </thead>
    <tbody>
        @foreach (PromoScript sc in Model)
        {
            <tr>
                @*<td>@sc.ScriptTemplate</td>*@
                <td>@Html.ActionLink(@sc.ScriptTemplate, "EditScript", "Script", new { @tId = @sc.ScriptTemplate }, null)</td>
                <td>@sc.ScriptName</td>
                <td>@sc.BiScriptCode</td>
                <td>@sc.Description</td>
                <td>@sc.CoreOfferSalesTax</td>
                <td>@sc.CrossSalesTax</td>
                
            </tr>
        }
    </tbody>
</table>